export const resourcesSectionContent = {
  en: {
    title: "Resources",
    subtitle: "Free guides and ebooks to help you grow as a professional.",
    download: "Download Free",
    getNow: "Get Now",
    new: "New",
    free: "Free",
    featured: "Featured",
    comingSoon: "Coming soon: more resources available",
    close: "Close",
    description: "Description",
    whatsIncluded: "What's Included",
    tags: "Tags",
    downloadLabel: "Download",
    viewLabel: "View",
  },
  es: {
    title: "Recursos",
    subtitle: "Guías y ebooks gratuitos para ayudarte a crecer como profesional.",
    download: "Descargar Gratis",
    getNow: "Obtener Ahora",
    new: "Nuevo",
    free: "Gratis",
    featured: "Destacado",
    comingSoon: "Próximamente: más recursos disponibles",
    close: "Cerrar",
    description: "Descripción",
    whatsIncluded: "Qué incluye",
    tags: "Etiquetas",
    downloadLabel: "Descargar",
    viewLabel: "Ver",
  },
} as const;
